"""Render the engagement into a pentest report (markdown + self-contained HTML)."""

from __future__ import annotations

import html
import time
from pathlib import Path

from riftor.engagement.cvss import base_score

_SEV_RANK = {"critical": 5, "high": 4, "medium": 3, "low": 2, "info": 1}
_SEV_ORDER = ["critical", "high", "medium", "low", "info"]
_STAGE_NAMES = {"R": "Recon", "I": "Intrusion", "F": "Foothold", "T": "Takeover"}


def report_data(engagement) -> dict:
    store = engagement.store
    findings = store.list_findings()
    for f in findings:
        vector = f.get("cvss") or ""
        f["cvss_score"] = base_score(vector) if vector else None
    findings.sort(
        key=lambda f: (
            -_SEV_RANK.get(f.get("severity", "info"), 0),
            -(f.get("cvss_score") or 0.0),
            f["id"],
        )
    )
    counts = {sev: 0 for sev in _SEV_ORDER}
    for f in findings:
        counts[f.get("severity", "info")] = counts.get(f.get("severity", "info"), 0) + 1

    workdir = engagement.dir.parent
    return {
        "title": store.get_meta("name") or workdir.name or "engagement",
        "generated": time.strftime("%Y-%m-%d %H:%M:%S"),
        "stage": engagement.stage,
        "stage_name": _STAGE_NAMES.get(engagement.stage, engagement.stage),
        "scope_in": [t.raw for t in engagement.scope.in_scope],
        "scope_out": [t.raw for t in engagement.scope.out_of_scope],
        "counts": counts,
        "findings": findings,
        "services": store.list_services(),
        "hosts": store.list_hosts(),
    }


def _cvss_label(finding: dict) -> str:
    score = finding.get("cvss_score")
    if score is None:
        return ""
    return f"{score:.1f}"


def build_markdown(data: dict) -> str:
    out: list[str] = []
    out.append(f"# {data['title']} — riftor report")
    out.append("")
    out.append(f"_Generated {data['generated']} · stage reached: {data['stage_name']}_")
    out.append("")

    out.append("## Scope")
    out.append(f"- **In scope:** {', '.join(data['scope_in']) or '(none)'}")
    if data["scope_out"]:
        out.append(f"- **Out of scope:** {', '.join(data['scope_out'])}")
    out.append("")

    out.append("## Summary")
    out.append("")
    out.append("| Severity | Count |")
    out.append("| --- | --- |")
    for sev in _SEV_ORDER:
        out.append(f"| {sev.capitalize()} | {data['counts'].get(sev, 0)} |")
    out.append(f"\n**Total findings:** {len(data['findings'])}")
    out.append("")

    out.append("## Findings")
    out.append("")
    if not data["findings"]:
        out.append("_No findings recorded._")
    for idx, f in enumerate(data["findings"], 1):
        cvss = _cvss_label(f)
        tag = f"{f.get('severity', 'info').upper()}"
        if cvss:
            tag += f" · CVSS {cvss}"
        out.append(f"### {idx}. [{tag}] {f['title']}")
        if f.get("host"):
            out.append(f"- **Host:** {f['host']}")
        if f.get("cvss"):
            out.append(f"- **CVSS:** {cvss} (`{f['cvss']}`)")
        if f.get("evidence"):
            out.append(f"- **Evidence:**\n\n```\n{f['evidence']}\n```")
        if f.get("recommendation"):
            out.append(f"- **Recommendation:** {f['recommendation']}")
        out.append("")

    if data["services"]:
        out.append("## Appendix — Hosts & Services")
        out.append("")
        out.append("| Host | Port | Proto | Service | Version |")
        out.append("| --- | --- | --- | --- | --- |")
        for s in data["services"]:
            out.append(
                f"| {s.get('host', '')} | {s.get('port') or ''} | {s.get('proto', '')} "
                f"| {s.get('service', '')} | {s.get('version', '')} |"
            )
        out.append("")

    out.append("---")
    out.append("_RIFT methodology · generated by riftor_")
    return "\n".join(out) + "\n"


_HTML_CSS = """
:root { color-scheme: dark; }
body { background:#0a0a12; color:#c8c8d4; font:15px/1.6 -apple-system,Segoe UI,Roboto,sans-serif;
       max-width:900px; margin:0 auto; padding:2rem; }
h1,h2,h3 { color:#e9e9f2; }
h1 { border-bottom:2px solid #a855f7; padding-bottom:.3rem; }
h2 { border-bottom:1px solid #2a2a3a; padding-bottom:.2rem; margin-top:2rem; }
a { color:#22d3ee; }
code,pre { background:#12121c; border-radius:4px; }
code { padding:.1rem .3rem; }
pre { padding:.8rem; overflow:auto; border-left:3px solid #22d3ee; }
table { border-collapse:collapse; width:100%; margin:.5rem 0; }
th,td { border:1px solid #2a2a3a; padding:.4rem .6rem; text-align:left; }
th { background:#14141f; color:#a855f7; }
.muted { color:#8b8ba7; }
.finding { border-left:4px solid #2a2a3a; padding:.2rem 1rem; margin:1rem 0; background:#101019; }
.sev-critical { border-left-color:#e11d48; }
.sev-high { border-left-color:#f0abfc; }
.sev-medium { border-left-color:#a855f7; }
.sev-low { border-left-color:#22d3ee; }
.sev-info { border-left-color:#4a4a5a; }
.badge { font-weight:700; }
"""


def build_html(data: dict) -> str:
    def esc(value) -> str:
        return html.escape(str(value))

    parts: list[str] = []
    parts.append("<!doctype html><html lang=en><head><meta charset=utf-8>")
    parts.append(f"<title>{esc(data['title'])} — riftor report</title>")
    parts.append(f"<style>{_HTML_CSS}</style></head><body>")
    parts.append(f"<h1>{esc(data['title'])} <span class=muted>— riftor report</span></h1>")
    parts.append(
        f"<p class=muted>Generated {esc(data['generated'])} · stage reached: "
        f"{esc(data['stage_name'])}</p>"
    )

    parts.append("<h2>Scope</h2><ul>")
    parts.append(f"<li><b>In scope:</b> {esc(', '.join(data['scope_in']) or '(none)')}</li>")
    if data["scope_out"]:
        parts.append(f"<li><b>Out of scope:</b> {esc(', '.join(data['scope_out']))}</li>")
    parts.append("</ul>")

    parts.append("<h2>Summary</h2><table><tr><th>Severity</th><th>Count</th></tr>")
    for sev in _SEV_ORDER:
        parts.append(f"<tr><td>{sev.capitalize()}</td><td>{data['counts'].get(sev, 0)}</td></tr>")
    parts.append("</table>")
    parts.append(f"<p><b>Total findings:</b> {len(data['findings'])}</p>")

    parts.append("<h2>Findings</h2>")
    if not data["findings"]:
        parts.append("<p class=muted>No findings recorded.</p>")
    for idx, f in enumerate(data["findings"], 1):
        sev = f.get("severity", "info")
        cvss = _cvss_label(f)
        tag = sev.upper() + (f" · CVSS {cvss}" if cvss else "")
        parts.append(f"<div class='finding sev-{esc(sev)}'>")
        parts.append(f"<h3>{idx}. <span class=badge>[{esc(tag)}]</span> {esc(f['title'])}</h3>")
        if f.get("host"):
            parts.append(f"<p><b>Host:</b> {esc(f['host'])}</p>")
        if f.get("cvss"):
            parts.append(f"<p><b>CVSS:</b> {esc(cvss)} (<code>{esc(f['cvss'])}</code>)</p>")
        if f.get("evidence"):
            parts.append(f"<p><b>Evidence:</b></p><pre>{esc(f['evidence'])}</pre>")
        if f.get("recommendation"):
            parts.append(f"<p><b>Recommendation:</b> {esc(f['recommendation'])}</p>")
        parts.append("</div>")

    if data["services"]:
        parts.append("<h2>Appendix — Hosts &amp; Services</h2>")
        parts.append("<table><tr><th>Host</th><th>Port</th><th>Proto</th><th>Service</th><th>Version</th></tr>")
        for s in data["services"]:
            parts.append(
                f"<tr><td>{esc(s.get('host', ''))}</td><td>{esc(s.get('port') or '')}</td>"
                f"<td>{esc(s.get('proto', ''))}</td><td>{esc(s.get('service', ''))}</td>"
                f"<td>{esc(s.get('version', ''))}</td></tr>"
            )
        parts.append("</table>")

    parts.append("<hr><p class=muted>RIFT methodology · generated by riftor</p>")
    parts.append("</body></html>")
    return "".join(parts)


def write_reports(engagement, fmt: str = "both") -> list[Path]:
    """Render and write report file(s). fmt in {md, html, both}. Returns paths."""
    data = report_data(engagement)
    out_dir = engagement.dir / "reports"
    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = time.strftime("%Y%m%d-%H%M%S")
    written: list[Path] = []

    if fmt in ("md", "both"):
        path = out_dir / f"report-{stamp}.md"
        path.write_text(build_markdown(data), encoding="utf-8")
        written.append(path)
    if fmt in ("html", "both"):
        path = out_dir / f"report-{stamp}.html"
        path.write_text(build_html(data), encoding="utf-8")
        written.append(path)
    return written
